\documentclass{article}
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{chemarrow}
\usepackage{subcaption}
\usepackage[margin=.5in]{geometry}

\begin{document}

\title{Data Analysis}
\author{Alexander Franks}
\date{\today}
\maketitle

Introduction to analysis.

\tableofcontents
\newpage

<<results='hide',echo=FALSE,warning=FALSE,message=FALSE,label=initialize,cache=TRUE>>=

    options(stringsAsFactors=FALSE)
opts_chunk$set(cache.path = 'cache/',fig.path = 'Figs/')

library(ggplot2)
library(scales)
library(corrplot)
library(RColorBrewer)
library(mvtnorm)
library(fdrtool)
library(xtable)
library(grid)
source("util_functions.R")

## data for the primary analysis comes from Wilhelm
focus.data <- "Wilhelm"
data2 <- "Kim"

mrna <- as.matrix(read.csv("mrna.csv",row.names=1))
msplit1 <- as.matrix(read.csv("mrna_split1.csv",row.names=1))
msplit2 <- as.matrix(read.csv("mrna_split2.csv",row.names=1))

protein <- as.matrix(read.csv(sprintf("protein_%s.csv",focus.data),row.names=1))
protein2 <- as.matrix(read.csv(sprintf("protein_%s.csv",data2),row.names=1))

tissue.names <- intersect(colnames(mrna),colnames(protein))
pretty.tissue.names <- sapply(tissue.names,strFormat)
n.tissues <- length(tissue.names)

gene.names <- intersect(rownames(mrna),rownames(protein))
n.genes <- length(gene.names)

mrna <- mrna[gene.names,tissue.names]
msplit1 <- msplit1[gene.names,tissue.names]
msplit2 <- msplit2[gene.names,tissue.names]
protein <- protein[gene.names,tissue.names]

tissue.ratios <- (10^protein)/(10^mrna)
median.ratios <- apply(tissue.ratios,1,function(x) median(x,na.rm=TRUE))
prediction.ratios <- log10((10^protein)/((10^mrna)*median.ratios))
predicted.raw <- (10^mrna)*median.ratios
@

\section*{Figure 1}

<<results='hide', fig.show='hide',label=figure-1,dependson=c("initialize"),echo=FALSE,warning=FALSE>>=

keep.indices <- which(log10(predicted.raw)!=protein)
cor.raw <- cor(log10(predicted.raw[keep.indices]),as.numeric(protein[keep.indices]))
    
png("Figs/1a_mrna_v_protein.png")
print(

    ggplot(data=data.frame(x=predicted.raw[keep.indices],y=10^as.numeric(protein[keep.indices])),aes(x=x,y=y))+
    geom_point(colour="blue",alpha=0.03)+
    scale_x_log10(breaks=10^(1:10),label=scientific_10,limits=c(10^2,10^8))+
    scale_y_log10(breaks=10^(1:10),labels=scientific_10,limits=c(10^2,10^8))+
    labs(x="Scaled mRNA",y="Measured Protein",title="")+
    annotate("text", x = 10^3, y = 10^7,label=as.character(as.expression(substitute(italic(R)[T]^2~"="~r2,list(r2=round(cor.raw^2,digits=2))))),parse=TRUE,size=10)+
    annotate("text", x = 10^3, y = 10^7.6,label=as.character(as.expression(substitute(italic(R)[T]~"="~r,list(r=round(cor.raw,digits=2))))),parse=TRUE,size=10)+
    theme(axis.title.x = element_text(face="bold",size=30),
          axis.text.x  = element_text(size=30),
          axis.title.y = element_text(face="bold",size=30),
          axis.text.y  = element_text(size=30,hjust=0)),
    )
dev.off()


rsquared.vec <- c()
negative.slopes <- c()
negative.slopes.vals <- c()
for(i in 1:nrow(protein)){
    if(sum(!is.na(predicted.raw[i,])&!is.na(protein[i,]))>1){
        lm.fit <- lm(protein[i,]~log10(predicted.raw)[i,])
        slope <- lm.fit$coefficients[2]
        rsq <- summary(lm.fit)$r.squared
        if(rsq<1 & sum(!is.na(predicted.raw[i,]*protein[i,]))>4)
            rsquared.vec <- c(rsquared.vec,rsq)
        if(slope<0){
            negative.slopes <- c(negative.slopes,i)
            negative.slopes.vals <- c(negative.slopes.vals,slope)
        }
    }
}



full.protein <- names(which(apply(protein[negative.slopes,],1,function(x) sum(!is.na(x)))==n.tissues&apply(predicted.raw[negative.slopes,],1,function(x) sum(!is.na(x)))==n.tissues))

sort(rowMeans(protein[full.protein,]))
focus.prot <- "ENSG00000111640"


mrna.vec <- as.numeric(t(log10(predicted.raw)))
protein.vec <- as.numeric(t(protein))
id <- rep(rownames(mrna),each=n.tissues)
df <- data.frame(x=mrna.vec,y=protein.vec,id=id)

mean.prot <- rowMeans(protein[full.protein,])
large.prots <- sample(names(mean.prot[mean.prot>6.5]),10)
sub.proteins <- unique(c(large.prots,sample(unique(id)[negative.slopes],100)))
       
df.sub <- df[df$id %in% sub.proteins,]
cor.segs <- cor(df.sub$x,df.sub$y,use="complete.obs")

pdf("Figs/1b_mrna_v_protein_segs_new.pdf",width=10,height=10)
print(
ggplot(data=df.sub,aes(x=x,y=y))+geom_smooth(method=lm,se=FALSE,aes(group=id),colour=alpha("black",0.5))+scale_x_continuous(breaks=1:10,label=function(x) parse(text=paste("10^", x)),limits=c(2,9))+
    scale_y_continuous(breaks=1:10,labels=function(x) parse(text=paste("10^", x)),limits=c(2,9))+
    labs(x="Scaled mRNA",y="Measured Protein")+
    annotate("text", x = 3, y = 8,label=as.character(as.expression(substitute(italic(R)[T]^2~"="~r2,list(r2=round(cor.segs^2,digits=2))))),parse=TRUE,size=10)+
    annotate("text", x = 3, y = 8.5,label=as.character(as.expression(substitute(italic(R)[T]~"="~r,list(r=round(cor.segs,digits=2))))),parse=TRUE,size=10)+
    theme(axis.title.x = element_text(face="bold",size=30),
          axis.text.x  = element_text(size=30),
          axis.title.y = element_text(face="bold",size=30),
          axis.text.y  = element_text(size=30,hjust=0))+
    geom_point(data=data.frame(x=log10(predicted.raw[focus.prot,]),y=protein[focus.prot,],Tissue=tissue.names),aes(x=x,y=y,label=length(tissue.names):1,color=Tissue),size=3)+#scale_colour_discrete(guide=FALSE)+
    theme(legend.text=element_text(size=15),legend.title.align=0.5,
          legend.background=element_rect(fill=alpha("gray", 0.5)),legend.key=element_blank(),legend.title=element_text(size=14)) +
    guides(colour = guide_legend(override.aes = list(size=5)))+
    geom_smooth(data=data.frame(x=log10(predicted.raw[focus.prot,]),y=protein[focus.prot,]),method=lm,se=FALSE,colour="black",size=1.5)+theme(legend.justification=c(1,0), legend.position=c(1,0)),
)
dev.off()

@

\begin{figure}
\centering
\begin{subfigure}{.4\textwidth}
  \centering
  \includegraphics[.4\textwidth]{\string Figs/1a_mrna_v_protein.png}
  \caption{A subfigure}
  \label{fig:sub1}
\end{subfigure}%
\begin{subfigure}{.4\textwidth}
  \centering
  \includegraphics[.4\textwidth]{\string Figs/1b_mrna_v_protein_segs_new.pdf}
  \caption{A subfigure}
  \label{fig:sub2}
\end{subfigure}
\caption{A figure with two subfigures}
\label{fig:test}
\end{figure}
  
\section*{Figure 2}

<<results='hide', fig.show='hide',label=figure-2,dependson=c("initialize"),echo=FALSE,warning=FALSE>>=


within.indices <- which(apply(!is.na(protein*predicted.raw),1,sum)>3)
within.cors <- sapply(within.indices,function(i) cor(protein[i,],log(predicted.raw)[i,],use="pairwise.complete.obs"))
between.cors <- sapply(1:ncol(protein),function(i) cor(protein[,i],log10(predicted.raw)[,i],use="pairwise.complete.obs"))
between.cors.raw <- sapply(1:ncol(protein),function(i) cor(protein[,i],mrna[,i],use="pairwise.complete.obs"))


## 
pdf("Figs/appendix_within_hist.pdf")
ggplot(data.frame(x=within.cors))+geom_histogram(aes(x=x,fill="within"),colour="black",binwidth=0.05,size=0.1)+labs(x=expression(paste("Correlation, ", R[P])),y="",title="Across Tissue, Empirical")+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_y_continuous(limits=c(0,300))+
    guides(fill=FALSE)
dev.off()



pdf("Figs/appendix_between_hists.pdf")
ggplot(data.frame(x=between.cors,x2=between.cors.raw,labels=tissue.names))+geom_histogram(aes(x=x,fill="Scaled"),binwidth=0.03,colour="black",size=0.1)+geom_histogram(aes(x=x2,fill="Raw"),binwidth=0.03,colour="black",size=0.1)+scale_x_continuous(limits=c(-1,1))+labs(x=expression(paste("Correlation, ", R[T])),y="",title="Within Tissue, Empirical")+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0),
          legend.text=element_text(size = 15, face = "bold"),
          legend.position=c(0.15,0.85))+
    guides(fill=guide_legend(title=NULL))

dev.off()

### Histogram of R-squared
pdf("Figs/histogram-rsq.pdf")
rsq.list <- data.frame(rsq=rsquared.vec)
ggplot(rsq.list,aes(x=rsq))+geom_histogram(binwidth=.05, colour="black", fill="grey")+labs(x="R-Squared",y="Count",title="Across Tissue, Empirical")+
    theme(axis.title.x = element_text(face="bold",size=30),
          axis.text.x  = element_text(size=16),
          axis.title.y = element_text(face="bold",size=30),
          axis.text.y  = element_text(size=16,hjust=0))
dev.off()


## Fisher transformation

n.pairwise <- rowSums(!is.na(protein*predicted.raw))
n.pairwise <- n.pairwise[n.pairwise>3]
ft <- fisher.transform(within.cors)

wts <- 1/(n.pairwise-3)
wts <- wts/sum(wts)
z <- sum(wts*ft)
pop.cor <- (exp(2*z)-1)/(exp(2*z)+1)
print(sprintf("Estimated population correlation: %.3f",pop.cor))

## Q- Value analysis
z.score<- (ft-pop.cor)*sqrt(n.pairwise-3)
fd.out <- fdrtool(z.score,plot=FALSE)

head(sort(fd.out$qval),n=20)
print(sprintf("Number of q-values < 0.01: %i",sum(fd.out$qval<0.01)))
print(sprintf("Number of q-values < 0.1: %i",sum(fd.out$qval<0.1)))

## simulate correlations
sim.within.cors <- sapply(1:length(z.score),function(i) cor(rmvnorm(n=n.pairwise[i],mean=c(0,0),sigma=matrix(c(1,pop.cor,pop.cor,1),nrow=2)))[1,2])
pdf("Figs/appendix_sim_within_hist.pdf")
ggplot(data.frame(x=sim.within.cors))+geom_histogram(aes(x=x,fill="within"),colour="black",binwidth=0.05,size=0.1)+labs(x=expression(paste("Correlation, ", R[P])),y="",title=expression(paste("Across Tissue, Simulated (",rho,"=0.35)",sep="")))+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_y_continuous(limits=c(0,300))+
    guides(fill=FALSE)
dev.off()


@ 

\begin{figure}
\centering
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/appendix_between_hists.pdf}
  \caption{A subfigure}
  \label{fig:sub1}
\end{subfigure}%
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/appendix_within_hist.pdf}
  \caption{A subfigure}
  \label{fig:sub2}
\end{subfigure}
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/appendix_sim_within_hist.pdf}
  \caption{}
  \label{fig:sub2}
\end{subfigure}
\caption{A figure with two subfigures}
\label{fig:test}
\end{figure}

\section*{Figure 5}

<<fig.width=4,fig.height=4,fig.align='center',label=figure-5, dependson("initialize"),echo=FALSE,warning=FALSE>>=

n.prot <- rowSums(!is.na(protein))
sd.prot.err <- uniroot(function(x) pnorm(log10(1.5),mean=0,sd=x)-0.75,lower=0,upper=10)$root
sd.prot.tot <- sqrt(sum((n.prot-1)*apply(protein,1,function(x) var(x,na.rm=TRUE)),na.rm=TRUE)/(sum(n.prot,na.rm=TRUE)-sum(n.prot>1)))
#sd.prot.tot <- median(apply(protein,1,function(x) sd(x,na.rm=TRUE)),na.rm=TRUE)
Rprot <- 1-sd.prot.err^2/sd.prot.tot^2

n.mrna <- rowSums(!is.na(mrna))
sd.mrna.err <- uniroot(function(x) pnorm(log10(1.2),mean=0,sd=x)-0.75,lower=0,upper=10)$root
## pooled estimator
sd.mrna.tot <- sqrt(sum((n.mrna-1)*apply(mrna,1,function(x) var(x,na.rm=TRUE)),na.rm=TRUE)/(sum(n.mrna,na.rm=TRUE)-sum(n.mrna>1)))
Rmrna <- 1-sd.mrna.err^2/sd.mrna.tot^2

pdf("Figs/5e-noise-correction.pdf")
mar2 <- par()$mar
mar2[2] <- 5.1
par(mar=mar2)

curve(sapply(x,function(fc){ 1-(uniroot(function(s) pnorm(log10(fc),mean=0,sd=s)-0.75,lower=0,upper=1000)$root)^2/sd.prot.tot^2}),from=1.00,to=1.5,
      ylab="Reliability",xlab="Median Fold Error (%)",
      lwd=3,main="",
      cex.lab=2,ylim=c(0,1),col="red",xaxt="n",cex.axis=2,cex.main=2)

grid()
text(1.37,0.6,"mRNA",col="blue",cex=1.5)
text(1.40,0.9,"protein",col="red",cex=1.5)
axis(1,at=seq(1,1.5,by=0.1),labels=c(0,10,20,30,40,50),cex.axis=2)

segments(1.2,0,1.2,Rmrna,col="dark grey",lwd=3)
segments(0,Rmrna,1.2,Rmrna,col="dark grey",lwd=3)
segments(1.5,0,1.5,Rprot,col="dark grey",lwd=3)
segments(0,Rprot,1.5,Rprot,col="dark grey",lwd=3)

curve(sapply(x,function(fc){ 1-(uniroot(function(s) pnorm(log10(fc),mean=0,sd=s)-0.75,lower=0,upper=1000)$root)^2/sd.mrna.tot^2}),from=1.00,to=1.5,cex.lab=2,lwd=3,add=TRUE,col="blue")

dev.off()

corrected.cor <- pop.cor/(Rprot*Rmrna)
corrected.rsq <- corrected.cor^2

Rprot.grid <- seq(pop.cor^2,1,by=0.01)
Rmrna.grid <- seq(pop.cor^2,1,by=0.01)
Rgrid <- expand.grid(Rprot.grid,Rmrna.grid)
rsq.grid <- matrix(pop.cor/sqrt(Rgrid[,1]*Rgrid[,2]),nrow=length(Rprot.grid))^2

rsq.grid[rsq.grid>1] <- 1
pdf("Figs/5e-noise-correction.pdf")
par(mar=c(6.1,5.1,4.1,2.1))
cols <- c("#08306B","#08519C","#2171B5","#4292C6","#9ECAE1")
cols2 <- rep(cols,each=2)
cols <- sapply(1:9,function(i) avg.colors(cols2[i],cols2[i+1]))

plot(0,xlim=c(pop.cor^2,1),ylim=c(pop.cor^2,1),xlab="Reliability of mRNA Measurements",ylab="Reliability of Protein Measurements",main="Fraction of Across-Tissue Protein Variance\n Explained By Transcript Levels",cex.lab=2,cex.axis=1.5,cex.main=1.5,xaxs="i",yaxs="i")
out.prev <- curve(pop.cor^2/x,from=0.1,to=1,col="red",lwd=3,n=1000,add=TRUE)
polygon(c(0,out.prev$x,1),c(0,out.prev$y,0),density = c(10, 20), angle = c(45, -45))
count <- 1
for(cur in seq(0.9,0.1,by=-0.1)){
    col <- cols[count]
    out.cur <- curve(pop.cor^2/(cur*x),from=0.1,to=1,lwd=1,lty=2,col="black",n=1000,add=TRUE)
    polygon(c(out.prev$x,rev(out.cur$x)),c(out.prev$y,rev(out.cur$y)),col=col,lty=0)
    out.prev <- out.cur
    count <- count+1
}
null.line <- curve(pop.cor^2/x,from=0.1,to=1,col="red",lwd=3,n=1000,add=TRUE)
text(0.9,0.9,"10",cex=1.5,col="dark grey",srt=-45)
text(0.75,0.72,"20",cex=1.5,col="dark grey",srt=-45)
text(0.65,0.6,"30",cex=1.5,col="dark grey",srt=-45)
text(0.58,0.53,"40",cex=1.5,col="dark grey",srt=-45)
text(0.52,0.47,"50",cex=1.5,col="dark grey",srt=-45)
text(0.48,0.43,"60",cex=1.2,col="dark grey",srt=-45)
text(0.45,0.40,"70",cex=1.2,col="dark grey",srt=-45)
text(0.43,0.37,"80",cex=1,col="dark grey",srt=-45)
text(0.41,0.35,"90",cex=1,col="dark grey",srt=-45)
rect(0.18,0.22,0.35,0.32,col="white",lty=1)
text(0.27,0.27,"100%",cex=2,col="dark grey")
dev.off() 

## Compute mrna reliabilities
mrna.reliabilities <- sapply(1:nrow(msplit1),function(i) cor(msplit1[i,],msplit2[i,],use="pairwise.complete.obs"))
    names(mrna.reliabilities) <- rownames(msplit1)
med.mrna <- median(mrna.reliabilities,na.rm=TRUE)
print(med.mrna)

pdf("Figs/mrna_reliabilities.pdf")
ggplot(data.frame(x=mrna.reliabilities))+geom_histogram(aes(x=x,fill="mRNA"),colour="black",binwidth=0.05,size=0.1)+labs(x="Reliability",y="",title=expression(paste("mRNA Reliabilities, Median = ",med.mrna,sep="")))+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_x_continuous(limits=c(0,1))+
    guides(fill=FALSE)
dev.off()

## Compute protein reliabilities
pcols <- intersect(colnames(protein),colnames(protein2))
prows <- intersect(rownames(protein),rownames(protein2))
cts <- apply(protein[prows,pcols]*protein2[prows,pcols],1,function(x) sum(!is.na(x)))
prows <- prows[cts>4]
protein.reliabilities <- sapply(prows,function(i) cor(protein[i,pcols],protein2[i,pcols],use="pairwise.complete.obs"))
med.prot <- median(protein.reliabilities,na.rm=TRUE)
print(med.prot)

pdf("Figs/protein_reliabilities.pdf")
ggplot(data.frame(x=protein.reliabilities))+geom_histogram(aes(x=x,fill="mRNA"),colour="black",binwidth=0.05,size=0.1)+labs(x="Reliability",y="",title=expression(paste("Protein Reliabilities, Median = ",med.prot,sep="")))+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_x_continuous(limits=c(-1,1))+
    guides(fill=FALSE)
dev.off()


## protein 2
p2.cors <- sapply(prows,function(i) cor(protein2[i,pcols],mrna[i,pcols],use="pairwise.complete.obs"))
med.p2 <- median(p2.cors,na.rm=TRUE)
print(med.p2)

tmp <- sapply(prows,function(i) cor((protein[i,pcols]+protein2[i,pcols])/2,mrna[i,pcols],use="pairwise.complete.obs"))

## TODO: FIGURE

@ 

\begin{figure}
\centering
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/mrna_reliabilities.pdf}
  \caption{mRNA reliability = \Sexpr{med.mrna}}
  \label{fig:sub1}
\end{subfigure}%
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/protein_reliabilities.pdf}
  \caption{Protein reliability = \Sexpr{med.prot}}
  \label{fig:sub2}
\end{subfigure}
\begin{subfigure}{.3\textwidth}
  \centering
  \includegraphics[width=\textwidth]{\string Figs/5a-fold_error_v_reliability.pdf}
  \caption{A subfigure}
  \label{fig:sub2}
\end{subfigure}
\caption{Noise corrected correlation = \Sexpr{pop.cor/sqrt(med.mrna*med.prot)}}
\label{fig:test}
\end{figure}


\section*{Figures S1}
<<fig.width=4,fig.height=4,fig.align='center',label=figure-s1, dependson("initialize"),echo=FALSE,warning=FALSE>>=

## noise corrected 
sd.mrnas <- apply(mrna, 1, function(x) sd(x,na.rm=TRUE))
sd.prots <- apply(protein, 1, function(x) sd(x,na.rm=TRUE))
## temporary
sd.mrnas.corrected <- sqrt(sd.mrnas^2*med.mrna)
sd.prots.corrected <- sqrt(sd.prots^2*med.prot)
sd.diffs.corrected <- sd.prots.corrected-sd.mrnas.corrected
summary(sd.diffs.corrected)
hist(sd.diffs.corrected,breaks=50)
abline(v=0,col="red")

pdf("Figs/physiological_sds.pdf")
ggplot(data.frame(x=sd.mrnas.corrected,x2=sd.prots.corrected),labels=c("mRNA","protein"))+geom_histogram(aes(x=x,fill="mRNA"),binwidth=0.03,colour="black",size=0.1,alpha=1)+geom_histogram(aes(x=x2,fill="protein"),binwidth=0.03,colour="black",size=0.1,alpha=0.5)+scale_x_continuous(limits=c(0,1.5))+labs(x="Standard Deviation",y="Count")+
    theme(axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.title.y = element_text(face="bold",size=25),
          axis.text.y  = element_text(size=16,hjust=0),
          legend.text=element_text(size = 20, face = "bold"),
          legend.position=c(0.8,0.9))+
         guides(fill=guide_legend(title=NULL))
dev.off()

pdf("Figs/sds-diff.pdf")
ggplot(data.frame(x=(sd.prots.corrected-sd.mrnas.corrected)))+geom_histogram(aes(x=x,fill="protein-mRNA"),binwidth=0.05,colour="black",size=0.1,alpha=1)+
    scale_x_continuous(limits=c(-1,1))+
labs(x="Difference in Standard Deviation",y="Count")+
    theme(axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.title.y = element_text(face="bold",size=25),
          axis.text.y  = element_text(size=16,hjust=0),
          legend.text=element_text(size = 20, face = "bold"),
          legend.position=c(0.8,0.9))+
     guides(fill=guide_legend(title=NULL))+geom_vline(xintercept=0,size=1.5)
dev.off()

@ 



\section*{Figure S2}

<<results='hide',fig.height=8,fig.width=12, label=figure-slope,dependson=c("initialize"),echo=FALSE,warning=FALSE>>=
slps <- c()
for(i in rownames(protein)){
    p <- protein[i,]
    m <- mrna[i,]
    notna <- which(!is.na(p*m))
    if(length(notna) > 5) {
        slps <- rbind(slps,lmodel2(p~m,range.x="interval",range.y="interval",nperm=1)$regression.results$Slope)
    }
}
colnames(slps) <- c("OLS","MA","SMA","RMA")
@ 

\section*{Figure X}

<<results='hide',fig.height=8,fig.width=12, label=figure-X,dependson=c("initialize"),echo=FALSE,warning=FALSE>>=

    grid.newpage()
pushViewport(viewport(layout = grid.layout(2,3)))

fold.comparison.tissues <- c("prostate","kidney","thyroid.gland")
fold.combos <- combn(fold.comparison.tissues,2)

for(i in 1:ncol(fold.combos)){

    t1 <- fold.combos[1,i]
    t2 <- fold.combos[2,i]

    pred <- log10(tissue.ratios[,t2]*10^mrna[,t1])
    raw <- protein[,t1]
    keep <- which(pred!=raw)
    pred <- pred[keep]
    raw <- raw[keep]
    cor.raw <- cor(pred,raw,use="complete.obs")^2
    
print(
        ggplot(data=data.frame(mrna=pred,protein=raw))+geom_point(aes(x=mrna,y=protein),colour="blue",alpha=0.3)+
        scale_x_continuous(breaks=1:10,labels=function(x) parse(text=paste("10^", x)),limits=c(2,8))+
        scale_y_continuous(breaks=1:10,labels=function(x) parse(text=paste("10^", x)),limits=c(2,8))+
        labs(x=sprintf("%s mRNA scaled by %s PTR",strFormat(t1),strFormat(t2)),
             y=sprintf("Measured protein in %s",strFormat(t1)))+
        annotate("text", x = 3, y = 7.5,label=as.character(as.expression(substitute(italic(R)~"="~r,list(r=format(cor.raw,digits=2))))),parse=TRUE,size=10)+
        annotate("text", x = 3, y = 7,label=as.character(as.expression(substitute(italic(R)^2~"="~r2,list(r2=format(cor.raw^2,digits=2))))),parse=TRUE,size=10)+
        theme(axis.title.x = element_text(face="bold",size=22),
          axis.text.x  = element_text(size=30),
          axis.title.y = element_text(face="bold",size=30),
              axis.text.y  = element_text(size=30,hjust=0)),
    vp=viewport(layout.pos.row=1,layout.pos.col=i)
    )

}

for(i in 1:ncol(fold.combos)){

    t1 <- fold.combos[1,i]
    t2 <- fold.combos[2,i]

    fold.cor <- cor(mrna[,t1]-mrna[,t2],protein[,t1]-protein[,t2],use="complete.obs")

    print(
        ggplot(data=data.frame(mrna=10^(mrna[,t1]-mrna[,t2]),protein=10^(protein[,t1]-protein[,t2])))+geom_point(aes(x=mrna,y=protein),colour="blue",alpha=0.3)+
    scale_x_log10(breaks=10^(-2:2),label=scientific_10,limits=c(10^-2,10^2))+
    scale_y_log10(breaks=10^(-3:3),labels=scientific_10,limits=c(10^-3,10^3))+
    labs(x="mRNA Fold Change",y="Protein Fold Change")+
    annotate("text", x = 10^-1.2, y = 10^2.5,label=as.character(as.expression(substitute(italic(R)~"="~r,list(r=round(fold.cor,digits=3))))),parse=TRUE,size=10)+
    annotate("text", x = 10^-1.2, y = 10^2,label=as.character(as.expression(substitute(italic(R)^2~"="~r2,list(r2=round(fold.cor^2,digits=3))))),parse=TRUE,size=10)+
    theme(axis.title.x = element_text(face="bold",size=30),
          axis.text.x  = element_text(size=30),
          axis.title.y = element_text(face="bold",size=30),
          axis.text.y  = element_text(size=30,hjust=0)),
        vp=viewport(layout.pos.row=2,layout.pos.col=i)        
 )
    
    
    
    
}
@ 





\section*{Figure 3}
<<results='hide',fig.height=5,fig.width=12,label=figure-3,dependson=c("initialize"),echo=FALSE,warning=FALSE>>=

par(mfrow=c(1,2))

cors.mat <- matrix(0,nrow=n.tissues,ncol=n.tissues)
rownames(cors.mat) <- colnames(cors.mat) <- tissue.names
combinations <- combn(tissue.names,2)
for(i in 1:ncol(combinations)){

    t1 <- combinations[1,i]
    t2 <- combinations[2,i]
    
    cr <- cor(mrna[,t1]-mrna[,t2],protein[,t1]-protein[,t2],use="pairwise.complete.obs")
    print(cr)
    
    cors.mat[combinations[1,i],combinations[2,i]] <- cors.mat[combinations[2,i],combinations[1,i]] <- cr

}
rownames(cors.mat) <- colnames(cors.mat) <- sapply(rownames(cors.mat),strFormat)

### Correlation Matrix Plot For Fold Changes
col.pal <- colorRampPalette(c("#7F0000","red","#FF7F00","yellow","#7FFF7F", 
                             "cyan", "#007FFF", "blue","#00007F"))

corrplot(cors.mat, method = "number",cl.lim=c(0,.6),col=col.pal(100),diag=FALSE,tl.col="black",tl.cex=1.5,cl.cex=1.2,cl.align.text="l",mar=c(5,0,0,0))


max.errors <- apply(prediction.ratios,1,function(x) max(abs(x),na.rm=TRUE))
mean.protein <- apply(protein,1,mean)[max.errors!=-Inf]
max.errors <- max.errors[max.errors!=-Inf]

cdf2 <- ecdf(max.errors)
par(mar=c(5.1,5.1,4.1,2.1))

plot(function(x) cdf2(x),xlab="Fold Error",ylab="Fraction of Genes",xlim=c(0,2),ylim=c(0.02,1),main="",lwd=3,panel.first=grid(nx=8,lwd=2),yaxt="n",xaxt="n",cex.lab=2,font.lab=2)

axis(1,cex.axis=1.5,labels=parse(text=paste("10^",seq(0,2,by=0.5))),at=seq(0,2,by=0.5))
axis(2,cex.axis=1.5)
segments(x0=1,y=0,x1=1,y1=cdf2(1),col="red",lwd=3,lty=2)
segments(x0=-.5,y=cdf2(1),x1=1,y1=cdf2(1),col="red",lwd=3,lty=2)
segments(x0=log10(2),y=0,x1=log10(2),y1=cdf2(log10(2)),col="blue",lwd=3,lty=2)
segments(x0=-.5,y=cdf2(log10(2)),x1=log10(2),y1=cdf2(log10(2)),col="blue",lwd=3,lty=2)

## Fraction exceeding 2 fold error
frac2 <- round(1-cdf2(log10(2)),digits=2)
## Number of proteins
n2 <- ceiling(frac2*length(max.errors))

## Fraction exceeding 10 fold error
frac10 <- round(1-cdf2(1),digits=2)
## Number of proteins 
n10 <- ceiling(frac10*length(max.errors))

@ 

\Sexpr{100*frac2} percent of protein (\Sexpr{n2} of
\Sexpr{nrow(protein)}) have a maximum error exceeding two-fold.
\Sexpr{100*frac10} percent of protein (\Sexpr{n10} of
\Sexpr{nrow(protein)}) have a maximum error exceeding ten-fold.


\section*{Supplement}

<<label=pop-cor,dependson("initialize"),echo=TRUE,warning=FALSE>>=

within.indices <- which(apply(!is.na(protein*predicted.raw),1,sum)>3)
within.cors <- sapply(within.indices,function(i) cor(protein[i,],log(predicted.raw)[i,],use="pairwise.complete.obs"))
between.cors <- sapply(1:ncol(protein),function(i) cor(protein[,i],log10(predicted.raw)[,i],use="pairwise.complete.obs"))
between.cors.raw <- sapply(1:ncol(protein),function(i) cor(protein[,i],mrna[,i],use="pairwise.complete.obs"))

n.pairwise <- rowSums(!is.na(protein*predicted.raw))
n.pairwise <- n.pairwise[n.pairwise>3]
ft <- fisher.transform(within.cors)

wts <- 1/(n.pairwise-3)
wts <- wts/sum(wts)
z <- sum(wts*ft)
pop.cor <- (exp(2*z)-1)/(exp(2*z)+1)

z.score<- (ft-pop.cor)*sqrt(n.pairwise-3)

fd.out <- fdrtool(z.score,plot=FALSE,verbose=FALSE)
@ 

%Number of q-values less than 1\%: \Sexpr{sum(fd.out$qval<0.01)}
%Number of q-values less than 10\%: \Sexpr{sum(fd.out$qval<0.1)}

<<fig.width=12,fig.height=4,fig.align='center',label=figure-S1, dependson("initialize"),echo=FALSE,warning=FALSE>>=

grid.newpage()
pushViewport(viewport(layout = grid.layout(1,3)))

## within tissue correlations
print(
    ggplot(data.frame(x=between.cors,x2=between.cors.raw,labels=tissue.names))+geom_histogram(aes(x=x,fill="Scaled"),binwidth=0.03,colour="black",size=0.1)+geom_histogram(aes(x=x2,fill="Raw"),binwidth=0.03,colour="black",size=0.1)+scale_x_continuous(limits=c(-1,1))+labs(x=expression(paste("Correlation, ", R[T])),y="",title="Within Tissue, Empirical")+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0),
          legend.text=element_text(size = 15, face = "bold"),
          legend.position=c(0.15,0.85))+
    guides(fill=guide_legend(title=NULL)),
    vp=viewport(layout.pos.row=1,layout.pos.col=1)
    )

## within gene correlations
print(
ggplot(data.frame(x=within.cors))+geom_histogram(aes(x=x,fill="within"),colour="black",binwidth=0.05,size=0.1)+labs(x=expression(paste("Correlation, ", R[P])),y="",title="Across Tissue, Empirical")+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_y_continuous(limits=c(0,300))+
    guides(fill=FALSE),
    vp=viewport(layout.pos.row=1,layout.pos.col=2)
)


## simulation within gene correlations
sim.within.cors <- sapply(1:length(z.score),function(i) cor(rmvnorm(n=n.pairwise[i],mean=c(0,0),sigma=matrix(c(1,pop.cor,pop.cor,1),nrow=2)))[1,2])

print(
ggplot(data.frame(x=sim.within.cors))+geom_histogram(aes(x=x,fill="within"),colour="black",binwidth=0.05,size=0.1)+labs(x=expression(paste("Correlation, ", R[P])),y="",title=expression(paste("Across Tissue, Simulated (",rho,"=0.35)",sep="")))+
    theme(title = element_text(size=20),
          axis.title.x = element_text(face="bold",size=25),
          axis.text.x  = element_text(size=16),
          axis.text.y  = element_text(size=16,hjust=0)) +
    scale_y_continuous(limits=c(0,300))+
    guides(fill=FALSE),
    vp=viewport(layout.pos.row=1,layout.pos.col=3)
)
@ 








<<fig.width=6,fig.height=6,fig.align='center',label=figure-S2,dependson=("initalize"),echo=FALSE,warning=FALSE,>>=

median.mrna <- median(as.vector(mrna),na.rm=TRUE)
te.mean <- apply(protein-mrna,1,function(x) median(x,na.rm=TRUE))

vgrid <- seq(0,0.5,by=0.01)
rsqgrid <- numeric(length(vgrid))
median.tissue.cor <- cors.full <- c()
count <- 1
for(vte in vgrid){

    efficiency_mat <- matrix(rnorm(n.genes*n.tissues,mean=rep(te.mean,n.tissues),sd=sqrt(vte)),ncol=n.tissues,nrow=nrow(protein))

    protein_mat <- mrna+efficiency_mat
    predicted.protein <- mrna+apply(efficiency_mat,1,median)

    keep <- !apply(protein_mat,1,function(x) all(is.na(x)))
    protein_mat <- protein_mat[keep,]
    predicted.protein <- predicted.protein[keep,]

    median.prot <- median(as.vector(protein_mat),na.rm=TRUE)
    half.indices <- protein_mat>median.prot

    cors.full <- c(cors.full,cor(as.vector(predicted.protein),as.vector(protein_mat),use="complete.obs"))

    median.tissue.cor <- c(median.tissue.cor,median(sapply(1:nrow(protein_mat),function(i) cor(predicted.protein[i,],protein_mat[i,],use="complete.obs")),na.rm=TRUE))

    rsqgrid[count] <- median(vte/apply(protein_mat,2,function(x) var(x,na.rm=TRUE)))
    count <- count+1
}


par(mar=c(6, 5.5, 4, 2))
plot(rsqgrid,cors.full^2,type="l",col="red",sub=expression(paste("Frac. of Unexplained Total Var., 1 - ",R[T]^2, "")),xlab="",ylab=expression(paste("R-Squared (",R^2,")")),font.axis=2,lwd=3,cex.lab=2,cex.sub=2,font.lab=2,font.axis=2,cex.axis=2,ylim=c(0,1),xlim=c(0,0.3))

real.frac <- median(apply(protein-mrna,1,function(x) var(x,na.rm=TRUE)),na.rm=TRUE)/apply(protein,2,function(x) var(x,na.rm=TRUE))
rect(min(real.frac), -1, max(real.frac), 2, density = NULL, col = "light grey",border=NA)

lines(rsqgrid,cors.full^2,col="red",lwd=3)
lines(rsqgrid,median.tissue.cor^2,lwd=3,cex.lab=2,font.lab=2,font.axis=2,cex.axis=1.5,col="blue",lty=2)

text(.25,0.85,c(expression(paste("",R[T]^2))),col="red",cex=2)
text(.25,.25,c(expression(paste("",R[P]^2))),col="blue",,cex=2)

@ 


\end{document}

